### PR TITLE
Optimize BGP route parsing by using os.scandir and writing routes to output file in a single operation

### PR DESCRIPTION
**Pull request by Mistersx12**
[s]This version of the script processes all the files in the input directory in a single pass and stores the routes and their AS paths in a list called routes. After processing all the files, it creates the paths-dir directory (if it doesn't already exist) and writes the contents of routes to a single output file called routes.txt.[/s]

Optimize BGP route parsing by using os.scandir to iterate through the input files and writing the routes and their AS paths to the output file in a single operation. This improves performance and reduces memory usage.

### CODE REVIEW

**Comment by brunoerg** [comment]
Hey, @Mistersx12! Glad to see you're interested on contributing to this project, I'm gonna review this PR soon. However, could you please change the PR title and commit message to a more specific one? "Update" doesn't say much about the changes. Thanks!

**Comment by brunoerg** [comment]
I took a look into the code, seems interesting, I'm running it to test, but I think we are gonna need another script to convert sets of dumps into a file with iprange->asn mappings (something like [bottleneck](https://github.com/sipa/asmap/blob/nextgen/bottleneck.py)). Aggregating them as you did here makes us having some duplicating ipranges, right?

**Comment by Mistersx12** [comment]
The script I provided extracts the routes and their AS paths from BGP dump files, but it does not aggregate or deduplicate the data. As a result, you may end up with duplicate routes in the output file if the same route appears in multiple BGP dump files.
To deduplicate the routes and create a mapping of IP ranges to ASNs could make sense

**Comment by Mistersx12** [comment]
I could write script that converts BGP dump files into a file with IP range to ASN mappings

**Review by brunoerg — APPROVED** [review]
ACK 08e4e7b3299dcef5f0d938cc8ada2a613f962b95

**Pull request merged**
